# Generated by Django 4.2.29 on 2026-03-19 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='英文名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类编码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '非遗分类',
                'verbose_name_plural': '非遗分类',
                'db_table': 'heritage_category',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Inheritor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='称号')),
                ('bio', models.TextField(blank=True, default='', verbose_name='简介')),
                ('bio_en', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': '传承人',
                'verbose_name_plural': '传承人',
                'db_table': 'heritage_inheritor',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='地域名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='英文名称')),
            ],
            options={
                'verbose_name': '地域',
                'verbose_name_plural': '地域',
                'db_table': 'heritage_region',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HeritageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=400)),
                ('summary', models.TextField(max_length=500, verbose_name='简介摘要')),
                ('summary_en', models.TextField(blank=True, default='', max_length=500)),
                ('description', models.TextField(verbose_name='详细描述 (Markdown)')),
                ('description_en', models.TextField(blank=True, default='')),
                ('history', models.TextField(blank=True, default='', verbose_name='历史背景')),
                ('history_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已下架')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='heritage.category', verbose_name='分类')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('inheritors', models.ManyToManyField(blank=True, related_name='heritage_items', to='heritage.inheritor', verbose_name='传承人')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='heritage.region')),
            ],
            options={
                'verbose_name': '非遗项目',
                'verbose_name_plural': '非遗项目',
                'db_table': 'heritage_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('heritage_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='heritage.heritageitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'heritage_favorite',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'heritage_item')},
            },
        ),
    ]
